<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Staff;

class StaffSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'name' => 'Dr. Christiany Juditha S.Sos., M.A.',
                'gender' => 'P',
                'birth_place' => 'Makassar',
                'birth_date' => '1971-05-20',
                'education' => 'S-3 ILMU KOMUNIKASI',
                'rank' => 'Pembina Tingkat I, IV/b',
                'position' => 'Kepala BBPSDMP Kominfo Medan',
            ],
            [
                'name' => 'Yusrizal,S.Kom.,M.Eng',
                'gender' => 'L',
                'birth_place' => 'MEDAN',
                'birth_date' => '1982-07-05',
                'education' => 'S-2 TEKNIK ELEKTRONIKA',
                'rank' => 'Pembina, IV/a',
                'position' => 'Kepala Bagian Umum',
            ],
            [
                'name' => 'Budiman, S.Sos',
                'gender' => 'L',
                'birth_place' => 'Tanjung Morawa',
                'birth_date' => '1971-03-05',
                'education' => 'S-1 ILMU KOMUNIKASI',
                'rank' => 'Pembina, IV/a',
                'position' => 'Analis Data Ilmiah Ahli Madya',
            ],
            [
                'name' => 'Frans Hendra Suryanta Sembiring,ST.,M.SM.',
                'gender' => 'L',
                'birth_place' => 'PEMATANGSIANTAR',
                'birth_date' => '1977-11-06',
                'education' => 'S-2 ILMU MANAJEMEN',
                'rank' => 'Pembina, IV/a',
                'position' => 'Pranata Humas Ahli Muda',
            ],
            [
                'name' => 'Meilinia Diakonia Ginting,S.Kom.',
                'gender' => 'P',
                'birth_place' => 'Brastagi',
                'birth_date' => '1981-05-03',
                'education' => 'S-1 ILMU KOMPUTER',
                'rank' => 'Penata Tk.I, III/d',
                'position' => 'Analis Tata Usaha',
            ],
            [
                'name' => 'Erwin Antonius Manurung, S.T.',
                'gender' => 'L',
                'birth_place' => 'MEDAN',
                'birth_date' => '1978-09-23',
                'education' => 'S-1 TEKNIK ELEKTRO',
                'rank' => 'Penata Tingkat I, III/d',
                'position' => 'Fasilitator Kemitraan',
            ],
            [
                'name' => 'Idawati Pandia,S.Sos.',
                'gender' => 'P',
                'birth_place' => 'Sukarya', // Image shows Sukaraya, but sometimes typos happen. I'll use image's.
                'birth_date' => '1971-08-15',
                'education' => 'S-1 ILMU KOMUNIKASI',
                'rank' => 'Penata Tk.I, III/d',
                'position' => 'Fasilitator Kemitraan',
            ],
            [
                'name' => 'Jarudo Damanik,S.Kom.',
                'gender' => 'L',
                'birth_place' => 'SIMALUNGUN',
                'birth_date' => '1976-06-05',
                'education' => 'S-1 TEKNIK INFORMATIKA',
                'rank' => 'Penata, III/c',
                'position' => 'Analis Perencanaan, Evaluasi dan Pelaporan',
            ],
            [
                'name' => 'Achmad Ofanny S. Torong,S.E.',
                'gender' => 'L',
                'birth_place' => 'MEDAN',
                'birth_date' => '1985-11-08',
                'education' => 'S-1 MANAJEMEN',
                'rank' => 'Penata, III/c',
                'position' => 'Penyusun Rencana Kebutuhan Rumah Tangga dan Perlengkapan',
            ],
            [
                'name' => 'Ahirinna, S.I.Kom.',
                'gender' => 'P',
                'birth_place' => 'TAPANULI SELATAN',
                'birth_date' => '1988-01-29',
                'education' => 'S-1 ILMU KOMUNIKASI',
                'rank' => 'Penata muda, III/a',
                'position' => 'Fasilitator Kemitraan',
            ],
            [
                'name' => 'Ghio Vani Debrian Soares, S.Pd.',
                'gender' => 'L',
                'birth_place' => 'LIMA PULUH KOTA',
                'birth_date' => '1994-09-24',
                'education' => 'S-1 TEKNOLOGI PENDIDIKAN',
                'rank' => 'Penata muda, III/a',
                'position' => 'Petugas Standarisasi dan Sertifikasi',
            ],
            [
                'name' => 'Ronald Rato Mangapul Limbong, SE.',
                'gender' => 'L',
                'birth_place' => 'DILI',
                'birth_date' => '1994-04-21',
                'education' => 'S-1 MANAJEMEN',
                'rank' => 'Penata muda, III/a',
                'position' => 'Analis Penjamin Mutu',
            ],
            [
                'name' => 'Eki Yoan Meydora, S.I.Kom.',
                'gender' => 'P',
                'birth_place' => 'Medan',
                'birth_date' => '1995-05-28',
                'education' => 'S-2 ILMU KOMUNIKASI',
                'rank' => 'Penata muda Tk I, III/b',
                'position' => 'Penyusun Bahan Informasi dan Publikasi',
            ],
            [
                'name' => 'Gusmila Zulidar, SE.',
                'gender' => 'P',
                'birth_place' => 'LABUHANBATU',
                'birth_date' => '1996-08-18',
                'education' => 'S-1 MANAJEMEN',
                'rank' => 'Penata muda, III/a',
                'position' => 'Petugas Standarisasi dan Sertifikasi',
            ],
            [
                'name' => 'Safrayuda Andrean, SE.',
                'gender' => 'L',
                'birth_place' => 'BINJAI',
                'birth_date' => '1996-06-22',
                'education' => 'S-1 MANAJEMEN',
                'rank' => 'Penata muda, III/a',
                'position' => 'Perencana Ahli Pertama',
            ],
            [
                'name' => 'Widia Apri Putri, S.Tr.Kom.',
                'gender' => 'P',
                'birth_place' => 'JAKARTA',
                'birth_date' => '1997-04-15',
                'education' => 'D-IV TEKNIK INFORMATIKA',
                'rank' => 'Penata muda, III/a',
                'position' => 'Pranata Komputer Ahli Pertama',
            ],
            [
                'name' => 'Darliandra, S.Stat.',
                'gender' => 'L',
                'birth_place' => 'BANDA ACEH',
                'birth_date' => '1997-09-18',
                'education' => 'S-1 STATISTIKA',
                'rank' => 'Penata muda, III/a',
                'position' => 'Statistisi Ahli Pertama',
            ],
            [
                'name' => 'Delvi Windrayani, S.I.Kom.',
                'gender' => 'P',
                'birth_place' => 'LANGKAT',
                'birth_date' => '1997-12-12',
                'education' => 'S-1 ILMU KOMUNIKASI',
                'rank' => 'Penata muda, III/a',
                'position' => 'Penyusun Bahan Informasi dan Publikasi',
            ],
            [
                'name' => 'Ade Gita Ellena Br. Tarigan, S.I.Kom.',
                'gender' => 'P',
                'birth_place' => 'DELI SERDANG',
                'birth_date' => '1998-10-29',
                'education' => 'S-1 ILMU KOMUNIKASI',
                'rank' => 'Penata muda, III/a',
                'position' => 'Penyusun Bahan Informasi dan Publikasi',
            ],
            [
                'name' => 'Michael Hariara Simanjuntak, S.Akun',
                'gender' => 'L',
                'birth_place' => 'MEDAN',
                'birth_date' => '1998-03-12',
                'education' => 'S-1 AKUNTANSI',
                'rank' => 'Penata muda, III/a',
                'position' => 'Penata Laporan Keuangan',
            ],
            [
                'name' => 'Jesty Meliana Sibarani, S.Akun',
                'gender' => 'P',
                'birth_place' => 'SERDANG BEDAGAI',
                'birth_date' => '1997-06-03',
                'education' => 'S-1 AKUNTANSI',
                'rank' => 'Penata muda, III/a',
                'position' => 'Penata Laporan Keuangan',
            ],
            [
                'name' => 'Alex Siregar,S.Kom.',
                'gender' => 'L',
                'birth_place' => 'PADANG SIDEMPUAN',
                'birth_date' => '1986-03-15',
                'education' => 'S-1 INFORMATIKA',
                'rank' => 'Penata Muda (PPPK) - IX',
                'position' => 'Penata Laporan Keuangan',
            ],
            [
                'name' => 'M. Prakoso Prabhaswara, S.Tr.Kom',
                'gender' => 'L',
                'birth_place' => 'BANDUNG',
                'birth_date' => '1996-01-25',
                'education' => 'D-IV TEKNOLOGI REKAYASA MULTIMEDIA',
                'rank' => 'Penata Muda (PPPK) - IX',
                'position' => 'Ahli Pertama - Pranata Komputer',
            ],
            [
                'name' => 'Ahmad Rozy,S.Kom., M.Kom.',
                'gender' => 'L',
                'birth_place' => 'MEDAN',
                'birth_date' => '1989-08-23',
                'education' => 'S-1 SISTEM INFORMASI',
                'rank' => 'Penata Muda (PPPK) - IX',
                'position' => 'Ahli Pertama - Instruktur',
            ],
            [
                'name' => 'Fachri Auliansyah,S.Kom.',
                'gender' => 'L',
                'birth_place' => 'MEDAN',
                'birth_date' => '1991-11-08',
                'education' => 'S-1 TEKNIK INFORMATIKA',
                'rank' => 'Penata Muda (PPPK) - IX',
                'position' => 'Penata Layanan Operasional',
            ],
            [
                'name' => 'Resky Datsita Sembiring Kembaren, S.Sos',
                'gender' => 'P',
                'birth_place' => 'MEDAN',
                'birth_date' => '1990-12-30',
                'education' => 'S-1 ILMU KOMUNIKASI',
                'rank' => 'Penata muda, III/a',
                'position' => 'Instruktur Ahli Pertama',
            ],
            [
                'name' => 'Siti Syafitri, S.Kom.',
                'gender' => 'P',
                'birth_place' => 'LANGKAT',
                'birth_date' => '2000-01-05',
                'education' => 'S-1 SISTEM INFORMASI',
                'rank' => 'Penata muda, III/a',
                'position' => 'Instruktur Ahli Pertama',
            ],
            [
                'name' => 'Aqilah Shabrina Nasution, S.Bns.',
                'gender' => 'P',
                'birth_place' => 'MEDAN',
                'birth_date' => '2003-02-23',
                'education' => 'S-1 BISNIS DIGITAL',
                'rank' => 'Penata muda, III/a',
                'position' => 'Instruktur Ahli Pertama',
            ],
            [
                'name' => 'Grace Silvia Anastasia Purba, S.Bns',
                'gender' => 'P',
                'birth_place' => 'PEMATANGSIANTAR',
                'birth_date' => '2001-09-27',
                'education' => 'S-1 BISNIS DIGITAL',
                'rank' => 'Penata muda, III/a',
                'position' => 'Instruktur Ahli Pertama',
            ],
            [
                'name' => 'Delpia Yesica Marpaung, S.Kom.',
                'gender' => 'P',
                'birth_place' => 'TOBA',
                'birth_date' => '2001-05-13',
                'education' => 'S-1 SISTEM INFORMASI',
                'rank' => 'Penata muda, III/a',
                'position' => 'Instruktur Ahli Pertama',
            ],
        ];

        foreach ($data as $item) {
            Staff::updateOrCreate(['name' => $item['name']], $item);
        }
    }
}
